api:
  host: localhost
  port: 8082
sql:
  host: 10.58.192.51
  port: 1433
  user: felipe.restum
  password: z12xcvab@#$

sqlLucca:
  host: localhost
  port: 1433
  user: sa
  password: <Luccasantos10@>

  